default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  username: postgres

development:
  <<: *default
  database: todo_development

test:
  <<: *default
  database: todo_test

production:
  <<: *default
  database: todo_production
